language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
cache:
  directories:
    - $HOME/.cache/pip
sudo: false
script:
  - coverage run --source=junebug `which trial` junebug
after_success:
  - coveralls
